# Generated by Django 6.0.4 on 2026-04-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videodata',
            name='collectCount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='收藏数量'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='commentCount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='评论数量'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='downloadCount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='下载数量'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='likeCount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='点赞数量'),
        ),
        migrations.AlterField(
            model_name='videodata',
            name='shareCount',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='分享数量'),
        ),
    ]
