# Generated by Django 6.0.4 on 2026-04-17 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户数据'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
