# Generated by Django 6.0.4 on 2026-04-27 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentdata',
            options={'verbose_name': '评论信息', 'verbose_name_plural': '评论数据'},
        ),
        migrations.AlterModelOptions(
            name='videodata',
            options={'verbose_name': '视频信息', 'verbose_name_plural': '视频数据'},
        ),
    ]
